services:
  - type: static
    name: employee-management-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://employee-management-system-c5qp.onrender.com 